/**/
SELECT COUNT(*) - COUNT(DISTINCT CITY) FROM STATION;

/**/
SELECT DISTINCT CITY
FROM STATION
WHERE MOD(ID, 2) = 0;

/**/
SELECT DISTINCT CITY
FROM STATION
WHERE MOD(ID, 2) = 0
ORDER BY CITY;

/**/
SELECT COUNT(*) - COUNT(DISTINCT CITY) AS Difference
FROM STATION;

/**/
SELECT CITY, LENGTH(CITY) AS NameLength
FROM STATION
ORDER BY NameLength, CITY
LIMIT 1;  

SELECT CITY, LENGTH(CITY) AS NameLength
FROM STATION
ORDER BY NameLength DESC, CITY
LIMIT 1;  

/**/
SELECT CITY FROM STATION
WHERE CITY LIKE 'A%' 
OR CITY LIKE 'E%'
OR CITY LIKE 'I%'
OR CITY LIKE 'O%'
OR CITY LIKE 'U%';
/* ou pode ser assim */
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(RIGHT(CITY, 1)) IN ('a', 'e', 'i', 'o', 'u');

/**/
SELECT DISTINCT CITY
FROM STATION
WHERE UPPER(LEFT(CITY, 1)) IN ('A', 'E', 'I', 'O', 'U')
AND LOWER(RIGHT(CITY, 1)) IN ('a', 'e', 'i', 'o', 'u');

/**/
SELECT DISTINCT CITY
FROM STATION
WHERE NOT LOWER(RIGHT(CITY, 1)) IN ('a', 'e', 'i', 'o', 'u');

/**/
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(LEFT(CITY, 1)) NOT IN ('a', 'e', 'i', 'o', 'u')
   OR LOWER(RIGHT(CITY, 1)) NOT IN ('a', 'e', 'i', 'o', 'u');

/**/
SELECT Name
FROM STUDENTS
WHERE Marks > 75
ORDER BY RIGHT(Name, 3), ID;
/**/

/**/